# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46d3260bc8717c63ee0cc17b6fdc142756e0aab461b1f1400508d4265b09a37c7bfff3e9eb3ba3563ab18e5fc99b4111aa8caa40a5d00d2121eb0958d99dbe6a

test:
  secret_key_base: 315d53365a71f32fa651f493b10f1ef300ee07bc361d06759be40cc4a4e56f46f2edcacc852abddddf03516c95629d18ffe45f4624271e3c472d5f3ad46f989a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
